name: Linux

on:
  pull_request:
  push:
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        kind: [static, shared]

    runs-on: ${{ matrix.os }}

    concurrency:
        group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-Linux-${{ matrix.kind }}
        cancel-in-progress: true
    steps:
      - uses: actions/checkout@v1

      - name: Installation
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc g++

      - name: Tests
        run: |
          ./configure
          make
          make run
